wootecam-gugucon/shopping-mall

src/main/java/com/gugucon/shopping/item/domain/entity/CartItem.java
src/main/java/com/gugucon/shopping/item/domain/entity/Product.java
src/main/java/com/gugucon/shopping/member/domain/entity/Member.java
src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
src/main/java/com/gugucon/shopping/order/domain/entity/OrderItem.java
src/main/java/com/gugucon/shopping/order/dto/response/OrderDetailResponse.java
src/main/java/com/gugucon/shopping/order/dto/response/OrderItemResponse.java
src/main/java/com/gugucon/shopping/pay/application/PayService.java
src/main/java/com/gugucon/shopping/pay/domain/Pay.java
src/main/resources/data.sql
src/main/resources/schema.sql
src/main/resources/templates/order-detail.html
src/main/resources/templates/order-history.html
src/test/java/com/gugucon/shopping/auth/JwtAuthenticationProviderTest.java
src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
src/test/java/com/gugucon/shopping/order/domain/entity/OrderTest.java
src/test/java/com/gugucon/shopping/pay/domain/PayTest.java
src/test/java/com/gugucon/shopping/pay/integration/PayIntegrationTest.java

#19 
- ERD 에 정의한 대로 스키마 생성 스크립트 (schema.sql) 작성
- `memberId` 에 fk 제약조건 추가
- 테이블 이름 전부 복수형으로 변경
- `pay` 테이블의 `price` 타입을 다른 테이블과 통일
- 모든 테이블이 `BaseTimeEntity` 를 상속받도록 수정
- 이상한 거 없는지 리뷰해주세요
- `application.properties` 에 다음 값 추가
```
spring.jpa.hibernate.ddl-auto=validate
```

feat: 데이터베이스 스키마 스크립트 추가

---

src/main/resources/static/js/login.js
src/main/resources/templates/cart.html
src/main/resources/templates/layouts/header.html

#44 
- 장바구니 sessionStorage 체크하는 것 localStorage로 변경
- 로그아웃 버튼 생성 및 로그인 / 로그아웃 시 (로그아웃) / (로그인, 회원가입) 버튼 토글되도록 변경
- 결국 자바스크립트로 했습니다.. ㅎㅎ

feat:프론트의 로그인 회원가입 인증 수정

---

src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
src/test/java/com/gugucon/shopping/integration/CartIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/OrderIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java

#34 
- ErrorCode 내에 404로 처리해야할 내용 변경

refactor: 존재하지 않는 상품, 장바구니 상품, 주문, 결제에 대한 상태코드 404로 수정

---

src/main/java/com/gugucon/shopping/order/domain/entity/Order.java

#43 
- Order 클래스 내 createOrderName 가독성 개선
- 과하다 싶거나 부족하다 싶은거 논의해보아요

refactor: OrderName 생성 로직 가독성 개선

---

src/main/java/com/gugucon/shopping/pay/controller/PayController.java
src/main/java/com/gugucon/shopping/pay/controller/PayPageController.java
src/main/java/com/gugucon/shopping/pay/dto/request/PayFailRequest.java
src/main/java/com/gugucon/shopping/pay/dto/response/PayFailResponse.java
src/main/java/com/gugucon/shopping/pay/service/PayService.java
src/main/resources/templates/pay-fail-popup.html
src/main/resources/templates/pay-success.html
src/main/resources/templates/signup.html
src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java

#42 
- 결제 실패시 주문 페이지로 이동하도록 변경
- 결제 실패시 통합 테스트 추가
- 프론트 페이지에 존재했던 마이너 에러 수정
- 프론트 확인,,, 마지막에 처음부터 끝까지 꼭 합시다

refactor: 결제 실패시 주문 페이지로 이동하도록 변경

---

src/main/resources/static/js/order.js
src/main/resources/templates/pay-fail-popup.html
src/main/resources/templates/pay-loading-popup.html

#60 
- 장바구니에 담긴 물품이 없을 때 /null로 이동하는 현상 해결
- 해당 현상 해결하면서 사용한 response.ok 다른 함수에도 적용

fix: 장바구니에 담긴 물품이 없을 때 /null 로 이동하는 현상 해결 

---

src/main/java/com/gugucon/shopping/item/controller/page/ProductPageController.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/main/resources/static/css/page/product.css
src/main/resources/static/js/pagination.js
src/main/resources/static/js/search.js
src/main/resources/templates/index.html
src/main/resources/templates/pay-fail-popup.html
src/main/resources/templates/search.html

#62 
- 상품 검색 결과 페이지 구현
- 페이지네이션 적용
- 정렬 키워드 선택 창 적용
- application.yml에 기본 데이터베이스 설정 추가
-

feat: 상품 검색 및 정렬 페이지 구현

---

src/main/java/com/gugucon/shopping/item/dto/response/CartItemResponse.java
src/main/resources/templates/cart.html

feat: 장바구니 물품이 품절이면 페이지에 품절 표시

---

Dockerfile

#77
- 컨테이너 이미지를 빌드하기 위한 Dockerfile 작성

feat: Dockerfile 작성

---

.github/workflows/cd.yml

#36
- Dockerfile(#77)로 컨테이너 이미지를 빌드해서 도커 허브에 푸시하면 이를 WAS 서버에서 받아서 동적으로 배포
- CD 워크플로우 작성

feat: CD 자동화

---

src/main/java/com/gugucon/shopping/auth/config/SecurityConfig.java
src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
src/main/java/com/gugucon/shopping/item/controller/api/RateController.java
src/main/java/com/gugucon/shopping/item/domain/entity/Rate.java
src/main/java/com/gugucon/shopping/item/dto/request/RateCreateRequest.java
src/main/java/com/gugucon/shopping/item/dto/response/RateResponse.java
src/main/java/com/gugucon/shopping/item/repository/RateRepository.java
src/main/java/com/gugucon/shopping/item/service/RateService.java
src/main/java/com/gugucon/shopping/order/dto/response/OrderItemResponse.java
src/main/java/com/gugucon/shopping/order/repository/OrderItemRepository.java
src/main/resources/schema.sql
src/test/java/com/gugucon/shopping/integration/PayIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
src/test/java/com/gugucon/shopping/utils/ApiUtils.java

#76 
- 별점 생성 API 구현
- 별점 조회 API 구현
- 화면 연동은 별도 이슈로 분리 예정
- 상태 코드가 적절한지 확인해주세요
- api 경로가 적절한지 확인해주세요

feat: 별점 기능 구현

---

src/main/java/com/gugucon/shopping/auth/domain/vo/JwtAuthenticationToken.java
src/main/java/com/gugucon/shopping/auth/dto/MemberPrincipal.java
src/main/java/com/gugucon/shopping/auth/security/JwtAuthenticationProvider.java
src/main/java/com/gugucon/shopping/item/controller/api/CartItemController.java
src/main/java/com/gugucon/shopping/member/domain/entity/Member.java
src/main/java/com/gugucon/shopping/member/domain/vo/Gender.java
src/main/java/com/gugucon/shopping/member/dto/request/SignupRequest.java
src/main/java/com/gugucon/shopping/member/service/MemberService.java
src/main/java/com/gugucon/shopping/order/controller/api/OrderController.java
src/main/java/com/gugucon/shopping/order/controller/api/OrderHistoryController.java
src/main/java/com/gugucon/shopping/pay/controller/PayController.java
src/main/java/com/gugucon/shopping/point/controller/PointController.java
src/main/java/com/gugucon/shopping/rate/controller/api/RateController.java
src/main/resources/schema.sql
src/main/resources/templates/signup.html
src/test/java/com/gugucon/shopping/auth/JwtAuthenticationProviderTest.java
src/test/java/com/gugucon/shopping/integration/AuthIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
src/test/java/com/gugucon/shopping/item/repository/ProductRepositoryTest.java
src/test/java/com/gugucon/shopping/utils/ApiUtils.java
src/test/java/com/gugucon/shopping/utils/DomainUtils.java

#108 
- Member 에 성별, 출생년도 정보 추가
- 스프링 시큐리티에서 조회하는 Principal 에 출생년도, 성별, 이메일, 닉네임 정보 추가
- 갱신된 Member 스키마에 따라 회원가입 api + 화면 수정

refactor: 시큐리티 principal 정보 수정

---

src/main/java/com/gugucon/shopping/item/domain/SortKey.java
src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
src/main/java/com/gugucon/shopping/item/service/ProductService.java
src/main/resources/static/js/search.js
src/main/resources/templates/search.html
src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
src/test/java/com/gugucon/shopping/utils/ApiUtils.java

#106 
- 별점 높은 순 구현 완료
- 최적화 어떻게 할지?

106 별점 높은순 정렬 구현

---

src/main/java/com/gugucon/shopping/rate/domain/entity/Rate.java
src/main/java/com/gugucon/shopping/rate/repository/RateRepository.java
src/main/java/com/gugucon/shopping/rate/service/RateService.java
src/main/resources/schema.sql

refactor: rate에 memberId 삭제

---

src/main/java/com/gugucon/shopping/common/exception/ErrorCode.java
src/main/java/com/gugucon/shopping/member/domain/vo/BirthYearRange.java
src/test/java/com/gugucon/shopping/member/domain/vo/BirthYearRangeTest.java

#114 
- BirthYearRange 추가
- 생년월일로 나이대 생성, 나이대로 탐색 범위 생성하는 로직 구현

feat: 나이대 정보와 생년월일 변환 로직 구현

---

src/main/java/com/gugucon/shopping/item/controller/api/ProductController.java
src/main/java/com/gugucon/shopping/item/domain/SortKey.java
src/main/java/com/gugucon/shopping/item/service/ProductService.java
src/main/java/com/gugucon/shopping/order/controller/api/OrderHistoryController.java
src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
src/main/java/com/gugucon/shopping/order/repository/OrderRepository.java
src/main/java/com/gugucon/shopping/order/service/OrderService.java
src/main/java/com/gugucon/shopping/pay/repository/PayRepository.java
src/main/resources/static/js/search.js
src/main/resources/templates/order-history.html
src/main/resources/templates/search.html
src/test/java/com/gugucon/shopping/integration/OrderHistoryIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
src/test/java/com/gugucon/shopping/utils/ApiUtils.java

#109 
- createdAt 정렬을 id 정렬로 수정하였습니다
- 주문 목록에 페이징을 적용하였습니다
- fetch + paging 적용 시에 메모리에서 페이징하는 이슈 해결을 위해 `@BatchSize` 적용

feat: 주문 목록 페이지네이션

---

src/main/resources/templates/login.html

refactor: 로그인 화면 영문 변경

---

src/main/java/com/gugucon/shopping/item/dto/response/CartItemResponse.java
src/main/java/com/gugucon/shopping/order/dto/response/OrderItemResponse.java
src/main/resources/templates/cart.html
src/main/resources/templates/index.html
src/main/resources/templates/order-detail.html
src/main/resources/templates/order-history-detail.html
src/main/resources/templates/order-history.html
src/main/resources/templates/pay-success.html
src/main/resources/templates/search.html

#92 
- 모든 페이지에서 상품 상세 페이지 접근 가능
- 상품 상세 페이지 접근시 상대 경로가 아닌 절대경로로 변경

refactor: 상품 상세 페이지에 전부 접근 가능

---

src/main/java/com/gugucon/shopping/item/domain/entity/OrderStat.java
src/main/java/com/gugucon/shopping/item/domain/entity/RateStat.java
src/main/java/com/gugucon/shopping/item/repository/OrderStatRepository.java
src/main/java/com/gugucon/shopping/item/repository/RateStatRepository.java
src/main/java/com/gugucon/shopping/item/repository/dto/SimpleOrderStatDto.java
src/main/java/com/gugucon/shopping/item/repository/dto/SimpleRateStatDto.java
src/main/java/com/gugucon/shopping/item/service/StatDataGenerator.java
src/main/resources/schema.sql

#121 
- 통계 테이블 스키마 및 엔티티를 작성했습니다.
- 클래스나 필드 이름은 임의로 작성했는데 더 나은 이름 있으면 의견 남겨주세요.

feat: 통계 테이블 스키마 작성

---

src/main/java/com/gugucon/shopping/member/repository/MemberRepository.java
src/main/java/com/gugucon/shopping/member/service/MemberService.java
src/main/java/com/gugucon/shopping/rate/controller/api/RateController.java
src/main/java/com/gugucon/shopping/rate/dto/response/RateDetailResponse.java
src/main/java/com/gugucon/shopping/rate/repository/RateRepository.java
src/main/java/com/gugucon/shopping/rate/service/RateService.java
src/main/resources/application-test.yml
src/test/java/com/gugucon/shopping/integration/LoginIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
src/test/java/com/gugucon/shopping/utils/ApiUtils.java

#90
- 내용
- 인수 테스트가 여러 명에 대해 회원가입 -> ... -> 별점 남기기 까지 필요해서 18초라는 시간(;;)이 걸리는 데 우선 올렸습니다.. 다음에 프론트와 연결할 때 다시 봐볼께요

feat: 현재 접속한 회원과 성별 및 나이대가 같은 주문들의 평균 별점 조회 기능 구현

---

src/main/java/com/gugucon/shopping/pay/dto/response/TossPayInfoResponse.java
src/main/java/com/gugucon/shopping/pay/service/PayService.java
src/main/resources/templates/pay-loading-popup.html
src/main/resources/templates/pay.html
src/test/java/com/gugucon/shopping/integration/TossPayIntegrationTest.java

#99 
- 토스 결제 customerEmail, customerName 삭제 및 memberRepository 의존성 제거
- 프론트 반영

refactor: 토스 결제 시 필요없는 데이터 제거

---

src/main/java/com/gugucon/shopping/member/domain/vo/BirthYearRange.java
src/main/java/com/gugucon/shopping/member/service/MemberService.java
src/test/java/com/gugucon/shopping/integration/SignupIntegrationTest.java
src/test/java/com/gugucon/shopping/member/domain/vo/BirthYearRangeTest.java

refactor: 회원가입시 나이 제약조건 추가

---

src/main/java/com/gugucon/shopping/member/domain/vo/BirthYearRange.java

#132 
- 회원가입 제약조건을 수정하여 테스트 통과하도록 변경

fix: 시작일을 포함하도록 제약 조건을 수정한다

---

src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
src/main/java/com/gugucon/shopping/order/domain/entity/Order.java
src/main/java/com/gugucon/shopping/order/repository/OrderRepository.java
src/main/java/com/gugucon/shopping/order/service/OrderService.java
src/main/java/com/gugucon/shopping/pay/service/PayService.java

#102 
- Product 조회 메서드에 비관적 락 추가

fix: 재고 감소 트랜잭션에 락 추가

---

src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java

#139 
- 별점 높은 순 정렬 countQuery 적용해서 약 1~2초 효율을 높인다
- 추가로 해야할 항목이 있을까요?

refactor: 별점 높은 순 정렬에 countQuery를 적용한다

---

src/main/java/com/gugucon/shopping/rate/service/RateService.java
src/main/resources/templates/product-detail.html
src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java

feat: 물품 상세 페이지에 현재 접속한 유저에 따른 평균 별점 항목 추가

---

src/main/java/com/gugucon/shopping/item/repository/ProductRepository.java
src/main/java/com/gugucon/shopping/rate/dto/response/RateResponse.java
src/main/java/com/gugucon/shopping/rate/repository/RateRepository.java
src/main/java/com/gugucon/shopping/rate/repository/dto/AverageRateDto.java
src/main/java/com/gugucon/shopping/rate/service/RateService.java
src/main/resources/schema.sql
src/test/java/com/gugucon/shopping/integration/ProductIntegrationTest.java
src/test/java/com/gugucon/shopping/integration/RateIntegrationTest.java
src/test/java/com/gugucon/shopping/item/repository/ProductRepositoryTest.java
src/test/java/com/gugucon/shopping/order/scheduler/OrderCancelServiceExecutionTest.java
src/test/java/com/gugucon/shopping/utils/DomainUtils.java
src/test/java/com/gugucon/shopping/utils/StatsUtils.java

#135 
- 별정 & 상품 조회에 통계 테이블 적용
- 테스트에 통계 정보 적용
- `stats` 테이블에 인덱스 추가 (`schema.sql` 확인해주세요 )
- 쿼리 잘 작성했는지 확인 해주십셔 ~~
- 통계 테이블 적용 이전-이후의 속도 차이는 노션에 기록했습니다 ~

refactor: 별점 & 상품 조회에 통계 테이블 적용

---

src/main/resources/static/css/common/index.css
src/main/resources/static/css/common/search.css
src/main/resources/static/css/page/product.css
src/main/resources/static/js/search.js
src/main/resources/templates/index.html
src/main/resources/templates/layouts/searchbar.html
src/main/resources/templates/search.html

142 성별 나이별 검색 필터링 기능 프론트 연동

---

build.gradle
src/main/resources/application.yml

#148 
- 대시보드 구축을 위해 actuator를 실행, 포트를 설정한다

148 모니터링 대시보드 구축

---

src/main/resources/templates/product-detail.html

#150 
- 화면에 적용된 flex css 를 제거했더니 해결되었습니다.

fix: 페이지 슬라이딩 제거
